/* Generated by Yosys 0.63 (git sha1 70a11c6bf, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* hdlname = "gcd" *)
(* top =  1  *)
(* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:11.1-102.10" *)
module gcd(clk, req_msg, req_rdy, req_val, reset, resp_msg, resp_rdy, resp_val);
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:13.15-13.18" *)
  input clk;
  wire clk;
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:14.24-14.31" *)
  input [31:0] req_msg;
  wire [31:0] req_msg;
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:15.15-15.22" *)
  output req_rdy;
  wire req_rdy;
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:16.15-16.22" *)
  input req_val;
  wire req_val;
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:17.15-17.20" *)
  input reset;
  wire reset;
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:18.24-18.32" *)
  output [15:0] resp_msg;
  wire [15:0] resp_msg;
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:19.15-19.23" *)
  input resp_rdy;
  wire resp_rdy;
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:20.15-20.23" *)
  output resp_val;
  wire resp_val;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:34.19-34.32" *)
  wire \ctrl$a_reg_en[0] ;
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:33.19-33.32" *)
  wire \ctrl$b_reg_en[0] ;
  wire \ctrl.state.out[1] ;
  wire \ctrl.state.out[2] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[0] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[10] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[11] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[12] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[13] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[14] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[15] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[1] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[2] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[3] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[4] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[5] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[6] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[7] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[8] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[9] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[0] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[10] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[11] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[12] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[13] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[14] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[15] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[1] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[2] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[3] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[4] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[5] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[6] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[7] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[8] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[9] ;
  (* hdlname = "dpath a_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:442.19-442.28" *)
  wire \dpath.a_mux$out[0] ;
  (* hdlname = "dpath a_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:442.19-442.28" *)
  wire \dpath.a_mux$out[10] ;
  (* hdlname = "dpath a_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:442.19-442.28" *)
  wire \dpath.a_mux$out[11] ;
  (* hdlname = "dpath a_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:442.19-442.28" *)
  wire \dpath.a_mux$out[12] ;
  (* hdlname = "dpath a_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:442.19-442.28" *)
  wire \dpath.a_mux$out[13] ;
  (* hdlname = "dpath a_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:442.19-442.28" *)
  wire \dpath.a_mux$out[14] ;
  (* hdlname = "dpath a_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:442.19-442.28" *)
  wire \dpath.a_mux$out[15] ;
  (* hdlname = "dpath a_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:442.19-442.28" *)
  wire \dpath.a_mux$out[1] ;
  (* hdlname = "dpath a_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:442.19-442.28" *)
  wire \dpath.a_mux$out[2] ;
  (* hdlname = "dpath a_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:442.19-442.28" *)
  wire \dpath.a_mux$out[3] ;
  (* hdlname = "dpath a_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:442.19-442.28" *)
  wire \dpath.a_mux$out[4] ;
  (* hdlname = "dpath a_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:442.19-442.28" *)
  wire \dpath.a_mux$out[5] ;
  (* hdlname = "dpath a_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:442.19-442.28" *)
  wire \dpath.a_mux$out[6] ;
  (* hdlname = "dpath a_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:442.19-442.28" *)
  wire \dpath.a_mux$out[7] ;
  (* hdlname = "dpath a_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:442.19-442.28" *)
  wire \dpath.a_mux$out[8] ;
  (* hdlname = "dpath a_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:442.19-442.28" *)
  wire \dpath.a_mux$out[9] ;
  (* hdlname = "dpath b_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:461.19-461.28" *)
  wire \dpath.b_mux$out[0] ;
  (* hdlname = "dpath b_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:461.19-461.28" *)
  wire \dpath.b_mux$out[10] ;
  (* hdlname = "dpath b_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:461.19-461.28" *)
  wire \dpath.b_mux$out[11] ;
  (* hdlname = "dpath b_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:461.19-461.28" *)
  wire \dpath.b_mux$out[12] ;
  (* hdlname = "dpath b_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:461.19-461.28" *)
  wire \dpath.b_mux$out[13] ;
  (* hdlname = "dpath b_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:461.19-461.28" *)
  wire \dpath.b_mux$out[14] ;
  (* hdlname = "dpath b_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:461.19-461.28" *)
  wire \dpath.b_mux$out[15] ;
  (* hdlname = "dpath b_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:461.19-461.28" *)
  wire \dpath.b_mux$out[1] ;
  (* hdlname = "dpath b_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:461.19-461.28" *)
  wire \dpath.b_mux$out[2] ;
  (* hdlname = "dpath b_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:461.19-461.28" *)
  wire \dpath.b_mux$out[3] ;
  (* hdlname = "dpath b_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:461.19-461.28" *)
  wire \dpath.b_mux$out[4] ;
  (* hdlname = "dpath b_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:461.19-461.28" *)
  wire \dpath.b_mux$out[5] ;
  (* hdlname = "dpath b_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:461.19-461.28" *)
  wire \dpath.b_mux$out[6] ;
  (* hdlname = "dpath b_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:461.19-461.28" *)
  wire \dpath.b_mux$out[7] ;
  (* hdlname = "dpath b_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:461.19-461.28" *)
  wire \dpath.b_mux$out[8] ;
  (* hdlname = "dpath b_mux$out" *)
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:461.19-461.28" *)
  wire \dpath.b_mux$out[9] ;
  sky130_fd_sc_hd__xnor2_1 _178_ (
    .A(\dpath.a_lt_b$in1[15] ),
    .B(\dpath.a_lt_b$in0[15] ),
    .Y(_003_)
  );
  sky130_fd_sc_hd__inv_1 _179_ (
    .A(\dpath.a_lt_b$in1[14] ),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nand2b_1 _180_ (
    .A_N(\dpath.a_lt_b$in1[13] ),
    .B(\dpath.a_lt_b$in0[13] ),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nor2b_1 _181_ (
    .A(\dpath.a_lt_b$in1[12] ),
    .B_N(\dpath.a_lt_b$in0[12] ),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand2b_1 _182_ (
    .A_N(\dpath.a_lt_b$in0[11] ),
    .B(\dpath.a_lt_b$in1[11] ),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nand2b_1 _183_ (
    .A_N(\dpath.a_lt_b$in0[12] ),
    .B(\dpath.a_lt_b$in1[12] ),
    .Y(_008_)
  );
  sky130_fd_sc_hd__o21ai_0 _184_ (
    .A1(_006_),
    .A2(_007_),
    .B1(_008_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nor2b_1 _185_ (
    .A(\dpath.a_lt_b$in0[13] ),
    .B_N(\dpath.a_lt_b$in1[13] ),
    .Y(_010_)
  );
  sky130_fd_sc_hd__a21oi_1 _186_ (
    .A1(_005_),
    .A2(_009_),
    .B1(_010_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__maj3_1 _187_ (
    .A(_004_),
    .B(\dpath.a_lt_b$in0[14] ),
    .C(_011_),
    .X(_012_)
  );
  sky130_fd_sc_hd__xnor2_1 _188_ (
    .A(_003_),
    .B(_012_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nor2b_1 _189_ (
    .A(\dpath.a_lt_b$in1[14] ),
    .B_N(\dpath.a_lt_b$in0[14] ),
    .Y(_014_)
  );
  sky130_fd_sc_hd__xnor2_1 _190_ (
    .A(_003_),
    .B(_014_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nor2b_1 _191_ (
    .A(\dpath.a_lt_b$in1[9] ),
    .B_N(\dpath.a_lt_b$in0[9] ),
    .Y(_016_)
  );
  sky130_fd_sc_hd__or2b_1 _192_ (
    .A(\dpath.a_lt_b$in0[9] ),
    .B_N(\dpath.a_lt_b$in1[9] ),
    .X(_017_)
  );
  sky130_fd_sc_hd__xnor2_1 _193_ (
    .A(\dpath.a_lt_b$in1[10] ),
    .B(\dpath.a_lt_b$in0[10] ),
    .Y(_018_)
  );
  sky130_fd_sc_hd__and3b_1 _194_ (
    .A_N(_016_),
    .B(_017_),
    .C(_018_),
    .X(_019_)
  );
  sky130_fd_sc_hd__inv_1 _195_ (
    .A(\dpath.a_lt_b$in1[8] ),
    .Y(_020_)
  );
  sky130_fd_sc_hd__inv_1 _196_ (
    .A(\dpath.a_lt_b$in1[7] ),
    .Y(_021_)
  );
  sky130_fd_sc_hd__inv_1 _197_ (
    .A(\dpath.a_lt_b$in1[6] ),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nor2b_1 _198_ (
    .A(\dpath.a_lt_b$in1[5] ),
    .B_N(\dpath.a_lt_b$in0[5] ),
    .Y(_023_)
  );
  sky130_fd_sc_hd__maj3_2 _199_ (
    .A(_022_),
    .B(\dpath.a_lt_b$in0[6] ),
    .C(_023_),
    .X(_024_)
  );
  sky130_fd_sc_hd__maj3_2 _200_ (
    .A(_021_),
    .B(\dpath.a_lt_b$in0[7] ),
    .C(_024_),
    .X(_025_)
  );
  sky130_fd_sc_hd__maj3_2 _201_ (
    .A(_020_),
    .B(\dpath.a_lt_b$in0[8] ),
    .C(_025_),
    .X(_026_)
  );
  sky130_fd_sc_hd__nor2b_1 _202_ (
    .A(\dpath.a_lt_b$in1[11] ),
    .B_N(\dpath.a_lt_b$in0[11] ),
    .Y(_027_)
  );
  sky130_fd_sc_hd__a21oi_1 _203_ (
    .A1(_008_),
    .A2(_027_),
    .B1(_006_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__a21oi_1 _204_ (
    .A1(_028_),
    .A2(_005_),
    .B1(_010_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__inv_1 _205_ (
    .A(\dpath.a_lt_b$in1[10] ),
    .Y(_030_)
  );
  sky130_fd_sc_hd__maj3_1 _206_ (
    .A(_030_),
    .B(\dpath.a_lt_b$in0[10] ),
    .C(_016_),
    .X(_031_)
  );
  sky130_fd_sc_hd__or2_2 _207_ (
    .A(_029_),
    .B(_031_),
    .X(_032_)
  );
  sky130_fd_sc_hd__nor2b_1 _208_ (
    .A(\dpath.a_lt_b$in0[2] ),
    .B_N(\dpath.a_lt_b$in1[2] ),
    .Y(_033_)
  );
  sky130_fd_sc_hd__inv_1 _209_ (
    .A(\dpath.a_lt_b$in0[1] ),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nor2b_1 _210_ (
    .A(\dpath.a_lt_b$in0[0] ),
    .B_N(\dpath.a_lt_b$in1[0] ),
    .Y(_035_)
  );
  sky130_fd_sc_hd__maj3_1 _211_ (
    .A(\dpath.a_lt_b$in1[1] ),
    .B(_034_),
    .C(_035_),
    .X(_036_)
  );
  sky130_fd_sc_hd__inv_1 _212_ (
    .A(\dpath.a_lt_b$in1[4] ),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nor2b_1 _213_ (
    .A(\dpath.a_lt_b$in1[2] ),
    .B_N(\dpath.a_lt_b$in0[2] ),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nor2b_1 _214_ (
    .A(\dpath.a_lt_b$in1[3] ),
    .B_N(\dpath.a_lt_b$in0[3] ),
    .Y(_039_)
  );
  sky130_fd_sc_hd__a211oi_1 _215_ (
    .A1(_037_),
    .A2(\dpath.a_lt_b$in0[4] ),
    .B1(_038_),
    .C1(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__o21ai_1 _216_ (
    .A1(_033_),
    .A2(_036_),
    .B1(_040_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__inv_1 _217_ (
    .A(\dpath.a_lt_b$in0[3] ),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nand2_1 _218_ (
    .A(\dpath.a_lt_b$in1[3] ),
    .B(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__maj3_1 _219_ (
    .A(_037_),
    .B(\dpath.a_lt_b$in0[4] ),
    .C(_043_),
    .X(_044_)
  );
  sky130_fd_sc_hd__nor2b_1 _220_ (
    .A(\dpath.a_lt_b$in1[8] ),
    .B_N(\dpath.a_lt_b$in0[8] ),
    .Y(_045_)
  );
  sky130_fd_sc_hd__and2b_1 _221_ (
    .A_N(\dpath.a_lt_b$in0[8] ),
    .B(\dpath.a_lt_b$in1[8] ),
    .X(_046_)
  );
  sky130_fd_sc_hd__xor2_1 _222_ (
    .A(\dpath.a_lt_b$in1[6] ),
    .B(\dpath.a_lt_b$in0[6] ),
    .X(_047_)
  );
  sky130_fd_sc_hd__xor2_1 _223_ (
    .A(\dpath.a_lt_b$in1[7] ),
    .B(\dpath.a_lt_b$in0[7] ),
    .X(_048_)
  );
  sky130_fd_sc_hd__nor4_1 _224_ (
    .A(_045_),
    .B(_046_),
    .C(_047_),
    .D(_048_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2b_1 _225_ (
    .A_N(\dpath.a_lt_b$in0[5] ),
    .B(\dpath.a_lt_b$in1[5] ),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nor2b_1 _226_ (
    .A(_023_),
    .B_N(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__and2_1 _227_ (
    .A(_049_),
    .B(_051_),
    .X(_052_)
  );
  sky130_fd_sc_hd__and4_1 _228_ (
    .A(_041_),
    .B(_044_),
    .C(_019_),
    .D(_052_),
    .X(_053_)
  );
  sky130_fd_sc_hd__a211oi_1 _229_ (
    .A1(_019_),
    .A2(_026_),
    .B1(_032_),
    .C1(_053_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__mux2i_1 _230_ (
    .A0(_013_),
    .A1(_015_),
    .S(_054_),
    .Y(resp_msg[15])
  );
  sky130_fd_sc_hd__nor2b_1 _231_ (
    .A(_054_),
    .B_N(_011_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__xor2_1 _232_ (
    .A(\dpath.a_lt_b$in1[14] ),
    .B(\dpath.a_lt_b$in0[14] ),
    .X(_056_)
  );
  sky130_fd_sc_hd__xnor2_1 _233_ (
    .A(_055_),
    .B(_056_),
    .Y(resp_msg[14])
  );
  sky130_fd_sc_hd__a211oi_2 _234_ (
    .A1(_019_),
    .A2(_026_),
    .B1(_031_),
    .C1(_053_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand2b_1 _235_ (
    .A_N(_010_),
    .B(_005_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__inv_1 _236_ (
    .A(\dpath.a_lt_b$in1[11] ),
    .Y(_059_)
  );
  sky130_fd_sc_hd__maj3_1 _237_ (
    .A(_059_),
    .B(\dpath.a_lt_b$in0[11] ),
    .C(_031_),
    .X(_060_)
  );
  sky130_fd_sc_hd__a21oi_1 _238_ (
    .A1(_008_),
    .A2(_060_),
    .B1(_006_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _239_ (
    .A(_009_),
    .B(_058_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__o21ai_0 _240_ (
    .A1(_058_),
    .A2(_061_),
    .B1(_062_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__and3_1 _241_ (
    .A(_041_),
    .B(_044_),
    .C(_052_),
    .X(_064_)
  );
  sky130_fd_sc_hd__nor2b_1 _242_ (
    .A(\dpath.a_lt_b$in0[12] ),
    .B_N(\dpath.a_lt_b$in1[12] ),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nor3_1 _243_ (
    .A(_065_),
    .B(_006_),
    .C(_058_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nor2b_1 _244_ (
    .A(_027_),
    .B_N(_007_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__o2111a_1 _245_ (
    .A1(_064_),
    .A2(_026_),
    .B1(_066_),
    .C1(_067_),
    .D1(_019_),
    .X(_068_)
  );
  sky130_fd_sc_hd__a311oi_1 _246_ (
    .A1(_028_),
    .A2(_057_),
    .A3(_058_),
    .B1(_063_),
    .C1(_068_),
    .Y(resp_msg[13])
  );
  sky130_fd_sc_hd__nor2_1 _247_ (
    .A(_065_),
    .B(_006_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__a31o_2 _248_ (
    .A1(_041_),
    .A2(_044_),
    .A3(_050_),
    .B1(_023_),
    .X(_070_)
  );
  sky130_fd_sc_hd__and3_1 _249_ (
    .A(_049_),
    .B(_019_),
    .C(_067_),
    .X(_071_)
  );
  sky130_fd_sc_hd__inv_1 _250_ (
    .A(\dpath.a_lt_b$in1[9] ),
    .Y(_072_)
  );
  sky130_fd_sc_hd__maj3_2 _251_ (
    .A(_072_),
    .B(\dpath.a_lt_b$in0[9] ),
    .C(_045_),
    .X(_073_)
  );
  sky130_fd_sc_hd__maj3_2 _252_ (
    .A(_030_),
    .B(\dpath.a_lt_b$in0[10] ),
    .C(_073_),
    .X(_074_)
  );
  sky130_fd_sc_hd__nor2_1 _253_ (
    .A(_045_),
    .B(_046_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nor2b_1 _254_ (
    .A(\dpath.a_lt_b$in1[6] ),
    .B_N(\dpath.a_lt_b$in0[6] ),
    .Y(_076_)
  );
  sky130_fd_sc_hd__maj3_1 _255_ (
    .A(_021_),
    .B(\dpath.a_lt_b$in0[7] ),
    .C(_076_),
    .X(_077_)
  );
  sky130_fd_sc_hd__and3_1 _256_ (
    .A(_075_),
    .B(_019_),
    .C(_077_),
    .X(_078_)
  );
  sky130_fd_sc_hd__or3_4 _257_ (
    .A(\dpath.a_lt_b$in0[11] ),
    .B(_074_),
    .C(_078_),
    .X(_079_)
  );
  sky130_fd_sc_hd__o21a_1 _258_ (
    .A1(_074_),
    .A2(_078_),
    .B1(\dpath.a_lt_b$in0[11] ),
    .X(_080_)
  );
  sky130_fd_sc_hd__a221oi_4 _259_ (
    .A1(_070_),
    .A2(_071_),
    .B1(_079_),
    .B2(_059_),
    .C1(_080_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__xnor2_1 _260_ (
    .A(_069_),
    .B(_081_),
    .Y(resp_msg[12])
  );
  sky130_fd_sc_hd__xnor2_1 _261_ (
    .A(_057_),
    .B(_067_),
    .Y(resp_msg[11])
  );
  sky130_fd_sc_hd__o31ai_1 _262_ (
    .A1(_016_),
    .A2(_064_),
    .A3(_026_),
    .B1(_017_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__xnor2_1 _263_ (
    .A(_018_),
    .B(_082_),
    .Y(resp_msg[10])
  );
  sky130_fd_sc_hd__nor2_1 _264_ (
    .A(_064_),
    .B(_026_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__xnor2_1 _265_ (
    .A(\dpath.a_lt_b$in0[9] ),
    .B(_083_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__xnor2_1 _266_ (
    .A(\dpath.a_lt_b$in1[9] ),
    .B(_084_),
    .Y(resp_msg[9])
  );
  sky130_fd_sc_hd__nor2_1 _267_ (
    .A(_047_),
    .B(_048_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__a21oi_1 _268_ (
    .A1(_085_),
    .A2(_070_),
    .B1(_077_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__xnor2_1 _269_ (
    .A(_075_),
    .B(_086_),
    .Y(resp_msg[8])
  );
  sky130_fd_sc_hd__maj3_1 _270_ (
    .A(_022_),
    .B(\dpath.a_lt_b$in0[6] ),
    .C(_070_),
    .X(_087_)
  );
  sky130_fd_sc_hd__xnor2_1 _271_ (
    .A(_048_),
    .B(_087_),
    .Y(resp_msg[7])
  );
  sky130_fd_sc_hd__xnor2_1 _272_ (
    .A(_047_),
    .B(_070_),
    .Y(resp_msg[6])
  );
  sky130_fd_sc_hd__nand2_1 _273_ (
    .A(_041_),
    .B(_044_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__xnor2_1 _274_ (
    .A(_088_),
    .B(_051_),
    .Y(resp_msg[5])
  );
  sky130_fd_sc_hd__nor2_1 _275_ (
    .A(_033_),
    .B(_036_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nor2_1 _276_ (
    .A(_038_),
    .B(_089_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__maj3_1 _277_ (
    .A(\dpath.a_lt_b$in1[3] ),
    .B(_042_),
    .C(_090_),
    .X(_091_)
  );
  sky130_fd_sc_hd__xnor2_1 _278_ (
    .A(\dpath.a_lt_b$in1[4] ),
    .B(\dpath.a_lt_b$in0[4] ),
    .Y(_092_)
  );
  sky130_fd_sc_hd__xnor2_1 _279_ (
    .A(_091_),
    .B(_092_),
    .Y(resp_msg[4])
  );
  sky130_fd_sc_hd__nor2b_1 _280_ (
    .A(_039_),
    .B_N(_043_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__xnor2_1 _281_ (
    .A(_090_),
    .B(_093_),
    .Y(resp_msg[3])
  );
  sky130_fd_sc_hd__nor2_1 _282_ (
    .A(_038_),
    .B(_033_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__xnor2_1 _283_ (
    .A(_036_),
    .B(_094_),
    .Y(resp_msg[2])
  );
  sky130_fd_sc_hd__xnor2_1 _284_ (
    .A(\dpath.a_lt_b$in1[1] ),
    .B(\dpath.a_lt_b$in0[1] ),
    .Y(_095_)
  );
  sky130_fd_sc_hd__xnor2_1 _285_ (
    .A(_035_),
    .B(_095_),
    .Y(resp_msg[1])
  );
  sky130_fd_sc_hd__xor2_1 _286_ (
    .A(\dpath.a_lt_b$in1[0] ),
    .B(\dpath.a_lt_b$in0[0] ),
    .X(resp_msg[0])
  );
  sky130_fd_sc_hd__clkbuf_1 _287_ (
    .A(req_rdy),
    .X(_096_)
  );
  sky130_fd_sc_hd__nand2b_1 _288_ (
    .A_N(_096_),
    .B(\ctrl.state.out[2] ),
    .Y(_097_)
  );
  sky130_fd_sc_hd__clkbuf_1 _289_ (
    .A(_097_),
    .X(_098_)
  );
  sky130_fd_sc_hd__nand2b_1 _290_ (
    .A_N(\dpath.a_lt_b$in0[15] ),
    .B(\dpath.a_lt_b$in1[15] ),
    .Y(_099_)
  );
  sky130_fd_sc_hd__inv_1 _291_ (
    .A(\dpath.a_lt_b$in1[13] ),
    .Y(_100_)
  );
  sky130_fd_sc_hd__maj3_1 _292_ (
    .A(_100_),
    .B(\dpath.a_lt_b$in0[13] ),
    .C(_006_),
    .X(_101_)
  );
  sky130_fd_sc_hd__maj3_1 _293_ (
    .A(_004_),
    .B(\dpath.a_lt_b$in0[14] ),
    .C(_101_),
    .X(_102_)
  );
  sky130_fd_sc_hd__nor2b_1 _294_ (
    .A(\dpath.a_lt_b$in1[15] ),
    .B_N(\dpath.a_lt_b$in0[15] ),
    .Y(_103_)
  );
  sky130_fd_sc_hd__a21oi_1 _295_ (
    .A1(_099_),
    .A2(_102_),
    .B1(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__o21ai_0 _296_ (
    .A1(_010_),
    .A2(_065_),
    .B1(_005_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nand2_1 _297_ (
    .A(\dpath.a_lt_b$in0[14] ),
    .B(_105_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nand2_1 _298_ (
    .A(\dpath.a_lt_b$in1[14] ),
    .B(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__or4_1 _299_ (
    .A(\dpath.a_lt_b$in0[14] ),
    .B(_103_),
    .C(_101_),
    .D(_066_),
    .X(_108_)
  );
  sky130_fd_sc_hd__o211a_1 _300_ (
    .A1(_103_),
    .A2(_107_),
    .B1(_108_),
    .C1(_099_),
    .X(_109_)
  );
  sky130_fd_sc_hd__a21bo_4 _301_ (
    .A1(_081_),
    .A2(_104_),
    .B1_N(_109_),
    .X(_110_)
  );
  sky130_fd_sc_hd__buf_12 _302_ (
    .A(_110_),
    .X(_111_)
  );
  sky130_fd_sc_hd__nor2_1 _303_ (
    .A(_098_),
    .B(_111_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__inv_1 _304_ (
    .A(\ctrl.state.out[2] ),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nor2_1 _305_ (
    .A(_096_),
    .B(_113_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__and3_1 _306_ (
    .A(\dpath.a_lt_b$in1[14] ),
    .B(_114_),
    .C(_111_),
    .X(_115_)
  );
  sky130_fd_sc_hd__and2_1 _307_ (
    .A(req_msg[30]),
    .B(_098_),
    .X(_116_)
  );
  sky130_fd_sc_hd__a211o_1 _308_ (
    .A1(resp_msg[14]),
    .A2(_112_),
    .B1(_115_),
    .C1(_116_),
    .X(\dpath.a_mux$out[14] )
  );
  sky130_fd_sc_hd__clkbuf_1 _309_ (
    .A(_098_),
    .X(_117_)
  );
  sky130_fd_sc_hd__buf_12 _310_ (
    .A(_111_),
    .X(_118_)
  );
  sky130_fd_sc_hd__mux2i_1 _311_ (
    .A0(resp_msg[13]),
    .A1(\dpath.a_lt_b$in1[13] ),
    .S(_118_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__clkbuf_1 _312_ (
    .A(_098_),
    .X(_120_)
  );
  sky130_fd_sc_hd__nand2_1 _313_ (
    .A(req_msg[29]),
    .B(_120_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__o21ai_1 _314_ (
    .A1(_117_),
    .A2(_119_),
    .B1(_121_),
    .Y(\dpath.a_mux$out[13] )
  );
  sky130_fd_sc_hd__o21a_1 _315_ (
    .A1(\dpath.a_lt_b$in0[12] ),
    .A2(_081_),
    .B1(_109_),
    .X(_122_)
  );
  sky130_fd_sc_hd__nor2_1 _316_ (
    .A(\dpath.a_lt_b$in1[12] ),
    .B(_122_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nor2_1 _317_ (
    .A(\dpath.a_lt_b$in0[12] ),
    .B(_104_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__mux2_2 _318_ (
    .A0(\dpath.a_lt_b$in0[12] ),
    .A1(_124_),
    .S(_081_),
    .X(_125_)
  );
  sky130_fd_sc_hd__nor3b_1 _319_ (
    .A(\dpath.a_lt_b$in1[12] ),
    .B(_124_),
    .C_N(_081_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__a31o_2 _320_ (
    .A1(\dpath.a_lt_b$in1[12] ),
    .A2(_109_),
    .A3(_125_),
    .B1(_126_),
    .X(_127_)
  );
  sky130_fd_sc_hd__nand2_1 _321_ (
    .A(req_msg[28]),
    .B(_120_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__o31ai_1 _322_ (
    .A1(_098_),
    .A2(_123_),
    .A3(_127_),
    .B1(_128_),
    .Y(\dpath.a_mux$out[12] )
  );
  sky130_fd_sc_hd__xnor2_1 _323_ (
    .A(\dpath.a_lt_b$in0[11] ),
    .B(_057_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__o21ai_1 _324_ (
    .A1(_118_),
    .A2(_129_),
    .B1(\dpath.a_lt_b$in1[11] ),
    .Y(_130_)
  );
  sky130_fd_sc_hd__or3_1 _325_ (
    .A(\dpath.a_lt_b$in1[11] ),
    .B(_110_),
    .C(_129_),
    .X(_131_)
  );
  sky130_fd_sc_hd__nor2_1 _326_ (
    .A(req_msg[27]),
    .B(_114_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__a31oi_1 _327_ (
    .A1(_114_),
    .A2(_130_),
    .A3(_131_),
    .B1(_132_),
    .Y(\dpath.a_mux$out[11] )
  );
  sky130_fd_sc_hd__mux2i_1 _328_ (
    .A0(resp_msg[10]),
    .A1(\dpath.a_lt_b$in1[10] ),
    .S(_118_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nand2_1 _329_ (
    .A(req_msg[26]),
    .B(_120_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__o21ai_1 _330_ (
    .A1(_117_),
    .A2(_133_),
    .B1(_134_),
    .Y(\dpath.a_mux$out[10] )
  );
  sky130_fd_sc_hd__nand2_1 _331_ (
    .A(req_msg[25]),
    .B(_120_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__o211ai_1 _332_ (
    .A1(_084_),
    .A2(_118_),
    .B1(_114_),
    .C1(\dpath.a_lt_b$in1[9] ),
    .Y(_136_)
  );
  sky130_fd_sc_hd__or4_1 _333_ (
    .A(\dpath.a_lt_b$in1[9] ),
    .B(_084_),
    .C(_098_),
    .D(_111_),
    .X(_137_)
  );
  sky130_fd_sc_hd__nand3_1 _334_ (
    .A(_135_),
    .B(_136_),
    .C(_137_),
    .Y(\dpath.a_mux$out[9] )
  );
  sky130_fd_sc_hd__xnor2_1 _335_ (
    .A(\dpath.a_lt_b$in0[8] ),
    .B(_086_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__o21ai_1 _336_ (
    .A1(_118_),
    .A2(_138_),
    .B1(\dpath.a_lt_b$in1[8] ),
    .Y(_139_)
  );
  sky130_fd_sc_hd__or3_1 _337_ (
    .A(\dpath.a_lt_b$in1[8] ),
    .B(_110_),
    .C(_138_),
    .X(_140_)
  );
  sky130_fd_sc_hd__nor2_1 _338_ (
    .A(req_msg[24]),
    .B(_114_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__a31oi_1 _339_ (
    .A1(_114_),
    .A2(_139_),
    .A3(_140_),
    .B1(_141_),
    .Y(\dpath.a_mux$out[8] )
  );
  sky130_fd_sc_hd__mux2i_1 _340_ (
    .A0(resp_msg[7]),
    .A1(\dpath.a_lt_b$in1[7] ),
    .S(_118_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nand2_1 _341_ (
    .A(req_msg[23]),
    .B(_120_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__o21ai_1 _342_ (
    .A1(_117_),
    .A2(_142_),
    .B1(_143_),
    .Y(\dpath.a_mux$out[7] )
  );
  sky130_fd_sc_hd__mux2i_1 _343_ (
    .A0(resp_msg[6]),
    .A1(\dpath.a_lt_b$in1[6] ),
    .S(_118_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nand2_1 _344_ (
    .A(req_msg[22]),
    .B(_120_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__o21ai_1 _345_ (
    .A1(_117_),
    .A2(_144_),
    .B1(_145_),
    .Y(\dpath.a_mux$out[6] )
  );
  sky130_fd_sc_hd__mux2i_1 _346_ (
    .A0(resp_msg[5]),
    .A1(\dpath.a_lt_b$in1[5] ),
    .S(_111_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nand2_1 _347_ (
    .A(req_msg[21]),
    .B(_120_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__o21ai_1 _348_ (
    .A1(_117_),
    .A2(_146_),
    .B1(_147_),
    .Y(\dpath.a_mux$out[5] )
  );
  sky130_fd_sc_hd__mux2i_1 _349_ (
    .A0(resp_msg[4]),
    .A1(\dpath.a_lt_b$in1[4] ),
    .S(_111_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__nand2_1 _350_ (
    .A(req_msg[20]),
    .B(_120_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__o21ai_1 _351_ (
    .A1(_117_),
    .A2(_148_),
    .B1(_149_),
    .Y(\dpath.a_mux$out[4] )
  );
  sky130_fd_sc_hd__mux2i_1 _352_ (
    .A0(resp_msg[3]),
    .A1(\dpath.a_lt_b$in1[3] ),
    .S(_111_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nand2_1 _353_ (
    .A(req_msg[19]),
    .B(_120_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__o21ai_1 _354_ (
    .A1(_117_),
    .A2(_150_),
    .B1(_151_),
    .Y(\dpath.a_mux$out[3] )
  );
  sky130_fd_sc_hd__mux2i_1 _355_ (
    .A0(resp_msg[2]),
    .A1(\dpath.a_lt_b$in1[2] ),
    .S(_111_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nand2_1 _356_ (
    .A(req_msg[18]),
    .B(_117_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__o21ai_0 _357_ (
    .A1(_117_),
    .A2(_152_),
    .B1(_153_),
    .Y(\dpath.a_mux$out[2] )
  );
  sky130_fd_sc_hd__mux2i_1 _358_ (
    .A0(resp_msg[1]),
    .A1(\dpath.a_lt_b$in1[1] ),
    .S(_111_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nand2_1 _359_ (
    .A(req_msg[17]),
    .B(_117_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__o21ai_0 _360_ (
    .A1(_098_),
    .A2(_154_),
    .B1(_155_),
    .Y(\dpath.a_mux$out[1] )
  );
  sky130_fd_sc_hd__nand2_1 _361_ (
    .A(req_msg[16]),
    .B(_120_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__inv_1 _362_ (
    .A(\dpath.a_lt_b$in0[0] ),
    .Y(_157_)
  );
  sky130_fd_sc_hd__o211ai_1 _363_ (
    .A1(_157_),
    .A2(_118_),
    .B1(_114_),
    .C1(\dpath.a_lt_b$in1[0] ),
    .Y(_158_)
  );
  sky130_fd_sc_hd__or4_1 _364_ (
    .A(\dpath.a_lt_b$in1[0] ),
    .B(_157_),
    .C(_098_),
    .D(_111_),
    .X(_159_)
  );
  sky130_fd_sc_hd__nand3_1 _365_ (
    .A(_156_),
    .B(_158_),
    .C(_159_),
    .Y(\dpath.a_mux$out[0] )
  );
  sky130_fd_sc_hd__clkbuf_1 _366_ (
    .A(_096_),
    .X(_160_)
  );
  sky130_fd_sc_hd__mux2_2 _367_ (
    .A0(\dpath.a_lt_b$in0[14] ),
    .A1(req_msg[14]),
    .S(_160_),
    .X(\dpath.b_mux$out[14] )
  );
  sky130_fd_sc_hd__mux2_2 _368_ (
    .A0(\dpath.a_lt_b$in0[13] ),
    .A1(req_msg[13]),
    .S(_160_),
    .X(\dpath.b_mux$out[13] )
  );
  sky130_fd_sc_hd__mux2_2 _369_ (
    .A0(\dpath.a_lt_b$in0[12] ),
    .A1(req_msg[12]),
    .S(_160_),
    .X(\dpath.b_mux$out[12] )
  );
  sky130_fd_sc_hd__mux2_2 _370_ (
    .A0(\dpath.a_lt_b$in0[11] ),
    .A1(req_msg[11]),
    .S(_160_),
    .X(\dpath.b_mux$out[11] )
  );
  sky130_fd_sc_hd__mux2_2 _371_ (
    .A0(\dpath.a_lt_b$in0[10] ),
    .A1(req_msg[10]),
    .S(_160_),
    .X(\dpath.b_mux$out[10] )
  );
  sky130_fd_sc_hd__mux2_2 _372_ (
    .A0(\dpath.a_lt_b$in0[9] ),
    .A1(req_msg[9]),
    .S(_160_),
    .X(\dpath.b_mux$out[9] )
  );
  sky130_fd_sc_hd__mux2_2 _373_ (
    .A0(\dpath.a_lt_b$in0[8] ),
    .A1(req_msg[8]),
    .S(_160_),
    .X(\dpath.b_mux$out[8] )
  );
  sky130_fd_sc_hd__mux2_2 _374_ (
    .A0(\dpath.a_lt_b$in0[7] ),
    .A1(req_msg[7]),
    .S(_160_),
    .X(\dpath.b_mux$out[7] )
  );
  sky130_fd_sc_hd__mux2_2 _375_ (
    .A0(\dpath.a_lt_b$in0[6] ),
    .A1(req_msg[6]),
    .S(_160_),
    .X(\dpath.b_mux$out[6] )
  );
  sky130_fd_sc_hd__mux2_2 _376_ (
    .A0(\dpath.a_lt_b$in0[5] ),
    .A1(req_msg[5]),
    .S(_160_),
    .X(\dpath.b_mux$out[5] )
  );
  sky130_fd_sc_hd__mux2_2 _377_ (
    .A0(\dpath.a_lt_b$in0[4] ),
    .A1(req_msg[4]),
    .S(_096_),
    .X(\dpath.b_mux$out[4] )
  );
  sky130_fd_sc_hd__clkbuf_1 _378_ (
    .A(_096_),
    .X(_161_)
  );
  sky130_fd_sc_hd__nand2_1 _379_ (
    .A(_161_),
    .B(req_msg[3]),
    .Y(_162_)
  );
  sky130_fd_sc_hd__o21ai_0 _380_ (
    .A1(_042_),
    .A2(_161_),
    .B1(_162_),
    .Y(\dpath.b_mux$out[3] )
  );
  sky130_fd_sc_hd__mux2_2 _381_ (
    .A0(\dpath.a_lt_b$in0[2] ),
    .A1(req_msg[2]),
    .S(_096_),
    .X(\dpath.b_mux$out[2] )
  );
  sky130_fd_sc_hd__nand2_1 _382_ (
    .A(_161_),
    .B(req_msg[1]),
    .Y(_163_)
  );
  sky130_fd_sc_hd__o21ai_0 _383_ (
    .A1(_034_),
    .A2(_161_),
    .B1(_163_),
    .Y(\dpath.b_mux$out[1] )
  );
  sky130_fd_sc_hd__nand2_1 _384_ (
    .A(_161_),
    .B(req_msg[0]),
    .Y(_164_)
  );
  sky130_fd_sc_hd__o21ai_0 _385_ (
    .A1(_157_),
    .A2(_161_),
    .B1(_164_),
    .Y(\dpath.b_mux$out[0] )
  );
  sky130_fd_sc_hd__mux2i_1 _386_ (
    .A0(resp_msg[15]),
    .A1(\dpath.a_lt_b$in1[15] ),
    .S(_118_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nor2_1 _387_ (
    .A(req_msg[31]),
    .B(_114_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__a21oi_1 _388_ (
    .A1(_114_),
    .A2(_165_),
    .B1(_166_),
    .Y(\dpath.a_mux$out[15] )
  );
  sky130_fd_sc_hd__inv_1 _389_ (
    .A(\ctrl.state.out[1] ),
    .Y(_167_)
  );
  sky130_fd_sc_hd__or2_2 _390_ (
    .A(_096_),
    .B(\ctrl.state.out[2] ),
    .X(\ctrl$a_reg_en[0] )
  );
  sky130_fd_sc_hd__nor2_1 _391_ (
    .A(_167_),
    .B(\ctrl$a_reg_en[0] ),
    .Y(resp_val)
  );
  sky130_fd_sc_hd__inv_1 _392_ (
    .A(req_val),
    .Y(_168_)
  );
  sky130_fd_sc_hd__a221o_1 _393_ (
    .A1(_161_),
    .A2(_168_),
    .B1(resp_rdy),
    .B2(resp_val),
    .C1(reset),
    .X(_000_)
  );
  sky130_fd_sc_hd__inv_1 _394_ (
    .A(resp_rdy),
    .Y(_169_)
  );
  sky130_fd_sc_hd__o21ai_0 _395_ (
    .A1(_161_),
    .A2(_169_),
    .B1(\ctrl.state.out[1] ),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nor4_1 _396_ (
    .A(\dpath.a_lt_b$in1[3] ),
    .B(\dpath.a_lt_b$in1[2] ),
    .C(\dpath.a_lt_b$in1[1] ),
    .D(\dpath.a_lt_b$in1[12] ),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nor4_1 _397_ (
    .A(\dpath.a_lt_b$in1[0] ),
    .B(\dpath.a_lt_b$in1[15] ),
    .C(\dpath.a_lt_b$in1[14] ),
    .D(\dpath.a_lt_b$in1[13] ),
    .Y(_172_)
  );
  sky130_fd_sc_hd__nor4_1 _398_ (
    .A(\dpath.a_lt_b$in1[11] ),
    .B(\dpath.a_lt_b$in1[10] ),
    .C(\dpath.a_lt_b$in1[9] ),
    .D(\dpath.a_lt_b$in1[4] ),
    .Y(_173_)
  );
  sky130_fd_sc_hd__nor4_1 _399_ (
    .A(\dpath.a_lt_b$in1[8] ),
    .B(\dpath.a_lt_b$in1[7] ),
    .C(\dpath.a_lt_b$in1[6] ),
    .D(\dpath.a_lt_b$in1[5] ),
    .Y(_174_)
  );
  sky130_fd_sc_hd__and4_1 _400_ (
    .A(_171_),
    .B(_172_),
    .C(_173_),
    .D(_174_),
    .X(_175_)
  );
  sky130_fd_sc_hd__o21ai_0 _401_ (
    .A1(\ctrl.state.out[1] ),
    .A2(_175_),
    .B1(\ctrl.state.out[2] ),
    .Y(_176_)
  );
  sky130_fd_sc_hd__a21oi_1 _402_ (
    .A1(_170_),
    .A2(_176_),
    .B1(reset),
    .Y(_001_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _403_ (
    .A1_N(_113_),
    .A2_N(_175_),
    .B1(req_val),
    .B2(_161_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__nor2_1 _404_ (
    .A(reset),
    .B(_177_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__a21o_1 _405_ (
    .A1(\ctrl.state.out[2] ),
    .A2(_118_),
    .B1(_161_),
    .X(\ctrl$b_reg_en[0] )
  );
  sky130_fd_sc_hd__mux2_2 _406_ (
    .A0(\dpath.a_lt_b$in0[15] ),
    .A1(req_msg[15]),
    .S(_096_),
    .X(\dpath.b_mux$out[15] )
  );
  sky130_fd_sc_hd__dfxtp_1 \ctrl.state.out[0]$_DFF_P_  (
    .CLK(clk),
    .D(_000_),
    .Q(req_rdy)
  );
  sky130_fd_sc_hd__dfxtp_1 \ctrl.state.out[1]$_DFF_P_  (
    .CLK(clk),
    .D(_001_),
    .Q(\ctrl.state.out[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 \ctrl.state.out[2]$_DFF_P_  (
    .CLK(clk),
    .D(_002_),
    .Q(\ctrl.state.out[2] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.a_reg.out[0]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.a_mux$out[0] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[0] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.a_reg.out[10]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.a_mux$out[10] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[10] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.a_reg.out[11]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.a_mux$out[11] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[11] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.a_reg.out[12]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.a_mux$out[12] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[12] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.a_reg.out[13]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.a_mux$out[13] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[13] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.a_reg.out[14]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.a_mux$out[14] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[14] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.a_reg.out[15]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.a_mux$out[15] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[15] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.a_reg.out[1]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.a_mux$out[1] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[1] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.a_reg.out[2]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.a_mux$out[2] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[2] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.a_reg.out[3]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.a_mux$out[3] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[3] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.a_reg.out[4]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.a_mux$out[4] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[4] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.a_reg.out[5]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.a_mux$out[5] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[5] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.a_reg.out[6]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.a_mux$out[6] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[6] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.a_reg.out[7]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.a_mux$out[7] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[7] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.a_reg.out[8]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.a_mux$out[8] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[8] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.a_reg.out[9]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.a_mux$out[9] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[9] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.b_reg.out[0]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.b_mux$out[0] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[0] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.b_reg.out[10]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.b_mux$out[10] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[10] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.b_reg.out[11]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.b_mux$out[11] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[11] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.b_reg.out[12]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.b_mux$out[12] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[12] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.b_reg.out[13]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.b_mux$out[13] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[13] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.b_reg.out[14]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.b_mux$out[14] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[14] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.b_reg.out[15]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.b_mux$out[15] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[15] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.b_reg.out[1]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.b_mux$out[1] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[1] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.b_reg.out[2]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.b_mux$out[2] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[2] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.b_reg.out[3]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.b_mux$out[3] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[3] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.b_reg.out[4]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.b_mux$out[4] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[4] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.b_reg.out[5]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.b_mux$out[5] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[5] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.b_reg.out[6]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.b_mux$out[6] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[6] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.b_reg.out[7]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.b_mux$out[7] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[7] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.b_reg.out[8]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.b_mux$out[8] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[8] )
  );
  (* src = "/home/aliu/Desktop/OpenROAD-flow-scripts/flow/designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__edfxtp_1 \dpath.b_reg.out[9]$_DFFE_PP_  (
    .CLK(clk),
    .D(\dpath.b_mux$out[9] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[9] )
  );
endmodule
